name: Test Go Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4t

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: run1
      run: go run -v cashloan/main.go
    
    - name: run2
      run: go run -v consumerloan/main.go

    - name: run3
      run: go run -v risk/main.go

    - name: run4
      run: go run -v gateway/main.go

    - name: test
      run: go test -v automation_test/gateway_test.go

    
        
