name: Test Go Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    # Cache Go modules to speed up builds
    - name: Cache Go modules for cashloan service
      uses: actions/cache@v3
      with:
        path: cashloan/pkg/mod
        key: ${{ runner.os }}-cashloan-go-${{ hashFiles('cashloan/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-cashloan-go-

    - name: Cache Go modules for consumerloan service
      uses: actions/cache@v3
      with:
        path: consumerloan/pkg/mod
        key: ${{ runner.os }}-consumerloan-go-${{ hashFiles('consumerloan/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-consumerloan-go-

    - name: Cache Go modules for risk service
      uses: actions/cache@v3
      with:
        path: risk/pkg/mod
        key: ${{ runner.os }}-risk-go-${{ hashFiles('risk/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-risk-go-

    - name: Cache Go modules for gateway service
      uses: actions/cache@v3
      with:
        path: gateway/pkg/mod
        key: ${{ runner.os }}-gateway-go-${{ hashFiles('gateway/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-gateway-go-

    # Install dependencies for each service
    - name: Install dependencies for cashloan service
      run: |
        cd cashloan
        go mod tidy

    - name: Install dependencies for consumerloan service
      run: |
        cd consumerloan
        go mod tidy

    - name: Install dependencies for risk service
      run: |
        cd risk
        go mod tidy

    - name: Install dependencies for gateway service
      run: |
        cd gateway
        go mod tidy

    # Build each service
    - name: Build cashloan service
      run: |
        cd cashloan
        go build -v .

    - name: Build consumerloan service
      run: |
        cd consumerloan
        go build -v .

    - name: Build risk service
      run: |
        cd risk
        go build -v .

    - name: Build gateway service
      run: |
        cd gateway
        go build -v .

    # Run each service (Make them listen on their respective ports)
    - name: Run cashloan service
      run: |
        cd cashloan
        ./cashloan &

    - name: Run consumerloan service
      run: |
        cd consumerloan
        ./consumerloan &

    - name: Run risk service
      run: |
        cd risk
        ./risk &

    - name: Run gateway service
      run: |
        cd gateway
        ./gateway &
    

    # Wait for the services to start
    - name: Wait for services to start
      run: sleep 5 # Adjust as needed

    # Run tests for the application
    - name: Run tests
      run: |
        cd automation_test
        go test -v gateway_test.go || exit 1

    - name: Fail Test Deny push
      run: exit 1
      if: failure()